# fly.toml app configuration file for tern-yuka-client
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tern-yuka-client'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1